### ISSUE TITLE
Preselected filter options are set always

### ISSUE THREAD

**Issue by nemstaa** [tpwd/ke_search#134] opened 2022-11-16 11:45 UTC
System: TYPO3 10.4.32
PHP 7.4
ke_search 4.5.1

If you select a preselected filter option in the "Searchbox and filters"-Plugin, the filter is set always. 
Switching the select input to show all, will reload the page, but the results are the same (in my case "news").
If you do not preselect a filter option, everything works fine. If you switch to the filter option, the results do change correctly.

Here are my settings:
[ke_search.pdf](https://github.com/tpwd/ke_search/files/10021215/ke_search.pdf)

Kind regards

**Comment by christianbltr** [comment] 2023-01-13 13:39
This seems to be a regression introduced with

https://github.com/tpwd/ke_search/commit/098ebf30cb4c54ccac62071abb87a30174306d6b

I will need to further investigate that.

**Comment by christianbltr** [comment] 2023-01-20 14:05
This has been fixed with https://github.com/tpwd/ke_search/commit/add3cb93c0c570f65b27bdb6edf28aa3bdbae5f6 in the current master version.

This also affects the routing configuration, see [Documentation/Configuration/RoutingSpeakingUrls.rst](https://github.com/tpwd/ke_search/commit/add3cb93c0c570f65b27bdb6edf28aa3bdbae5f6#diff-4df14275bdd91be559ccf5c988e352bd5f89da95790065d9015f1a32e60ca97f)

see also https://github.com/tpwd/ke_search/issues/126

**Closed by christianbltr** 2023-01-20 14:05 UTC
