### ISSUE TITLE
indexed pdf with images have a problem in preview in search result!

### ISSUE THREAD

**Issue by kbenyedder** [tpwd/ke_search#111] opened 2022-06-10 13:53 UTC
**Typo3 Version 10.4.27
ke_search  Version 4.4.4**

![image](https://user-images.githubusercontent.com/66422450/173080608-3717d191-9914-49df-9700-ffcbe4a29535.png)
[kvb-broschuere-niederlassungsleitfaden-fachaerzte.pdf](https://github.com/tpwd/ke_search/files/8879436/kvb-broschuere-niederlassungsleitfaden-fachaerzte.pdf)

see content in  the db 
[export.zip](https://github.com/tpwd/ke_search/files/8879465/export.zip)

Greetings beny

**Comment by kbenyedder** [comment] 2022-06-13 10:58
@christianbltr can you do something here please ?

**Comment by christianbltr** [comment] 2022-06-17 07:37
Hey Beny,

I could not reproduce the issue. I think will depend on the `catdoc` version which is installed on the server or some other server settings. I my case I tested it in a ddev environment with catdoc 0.95 installed.

Without applying your patch I get the following result:

![Auswahl_047](https://user-images.githubusercontent.com/11410553/174249433-096cb263-7f57-4c2a-a038-92afd0fb4019.png)

So I think this should rather be solved server-side, not inside ke_search.

**Comment by christianbltr** [comment] 2022-06-17 07:42
Sorry, I was a bit too fast here. I overlooked that you search for "Verordnung". In that case I can reproduce the issue.

**Comment by kbenyedder** [comment] 2022-06-17 07:51
yes please look into the content field of the table tx_kesearch_index.
Unfortunately we habe to filter (U+FFFD) characters .

**Comment by christianbltr** [comment] 2022-06-17 07:57
Patch is merged, thank you.

**Closed by christianbltr** 2022-06-17 07:57 UTC
