### ISSUE TITLE
PHP warning

### ISSUE THREAD

**Issue by mikeemike7** [tpwd/ke_search#151] opened 2023-04-06 08:58 UTC
Hi,
a PHP error message appears:
Core: Error handler (FE): PHP Warning: Undefined array key "highlightSword" in /www/htdocs/w0102030405/cmstypo3/typo3conf/ext/ke_search/Classes/Lib/Searchresult.php line 109

Any idea where I can start?

Typo3 11.5.25 php 8.1

Greetings,
Mike

**Comment by christianbltr** [comment] 2023-04-21 07:32
This should be fixed with https://github.com/tpwd/ke_search/commit/7f3b953d8186f01a551576563e7dd9f884e1406a. 

Could you try version 4.6.4?

**Comment by larsgoo** [comment] 2023-04-23 10:48
Hello,

Instead of a new issue I'll try here because I think its related...
after switching my PHP from 7.4 to 8.x I can no longer get to my search results page without an error:

PHP Warning: Undefined array key "resultsPerPage" in /var/www/html/htdocs/typo3conf/ext/ke_search/Classes/Lib/Db.php line 551

PHP Version: 8.1.33
TYPO3 Version: 11.5.26
ke_search Version: 4.6.4

Setup on my site seems to be fine and worked without issues in PHP 7.4:
- the search results page contains Pi1 (searchbox) and Pi2 (results).
- In the plugin flexform settings, 'resultsPerPage' is set to '10'.
- I can eliminate my custom templates as source of the problem; when reverting to the default ke_search templates I still get the error.

Any PHP version >= 8.0 will get me this error when visiting the search results page. I can reproduce this behaviour in two separate TYPO3 v11 projects by switching from PHP 7.4 to 8.x.

If you need more information let me know. 
Thanks for your help and your good work!

**Comment by mikeemike7** [comment] 2023-04-23 17:08
For me version 4.6.4 fixed the problem.
Thanks for this great extension!
:-)

**Comment by fe-hicking** [comment] 2023-04-24 15:28
Hey there. The issue reported by @larsgoo actually stemmed from another Exception not covered by the update of 4.6.4 and is actually a seperate issue.

We tried to create the Pull Request linked to this issue. We hope it helps, the writeup is contained in there. :-)

**Comment by ste101** [comment] 2023-07-07 09:28
Same here:
PHP Warning: Undefined array key "resultsPerPage" in /html/typo3/typo3conf/ext/ke_search/Classes/Lib/Db.php line 573
TYPO3 12.4.2
PHP 8.2
ke_search 5.0.2

**Closed** 2023-10-06 13:14 UTC
